version: '3.8'

services:
  rto-ai:
    build: .
    container_name: rto-ai-app
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: rto-nginx
    ports:
      - "92:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html   # 🔹 UI folder
    depends_on:
      - rto-ai
    restart: always