server {
    listen 92;

    client_max_body_size 20M;   # for file upload (your app uses 16MB)

    location / {
        proxy_pass http://rto-ai:5000;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_connect_timeout 60;
        proxy_send_timeout 60;
        proxy_read_timeout 60;

        # Fix for large responses / headers (you had this issue before)
        proxy_buffers 16 16k;
        proxy_buffer_size 32k;
    }
}